# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.comunica_post_pubblicazione_api import ComunicaPostPubblicazioneApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComunicaPostPubblicazioneApi(unittest.TestCase):
    """ComunicaPostPubblicazioneApi unit test stubs"""

    def setUp(self):
        self.api = ComunicaPostPubblicazioneApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_id_scheda_cancella(self):
        """Test case for id_scheda_cancella

        API Rest per l'eliminazione di una specifica Scheda dati in lavorazione nelle fasi successive alla pubblicazione. SINCRONO  # noqa: E501
        """
        pass

    def test_id_scheda_conferma(self):
        """Test case for id_scheda_conferma

        API Rest per la conferma dei dati inviati per una specifica Scheda. ASINCRONO - ASIMMETRICO  # noqa: E501
        """
        pass

    def test_id_scheda_crea(self):
        """Test case for id_scheda_crea

        API Rest generica per l'inserimento di una scheda dati per le fasi successive alla pubblicazione. SINCRONO  # noqa: E501
        """
        pass

    def test_id_scheda_dettaglio(self):
        """Test case for id_scheda_dettaglio

        API Rest per il recupero del dettaglio di una specifica Scheda dati. SINCRONO  # noqa: E501
        """
        pass

    def test_id_scheda_modifica(self):
        """Test case for id_scheda_modifica

        API Rest generica per la modifica di una scheda dati per le fasi successive alla pubblicazione. SINCRONO  # noqa: E501
        """
        pass

    def test_id_scheda_ricerca(self):
        """Test case for id_scheda_ricerca

        API Rest per la ricerca delle Schede dati inserite nelle fasi successive alla pubblicazione. SINCRONO  # noqa: E501
        """
        pass

    def test_id_scheda_verifica(self):
        """Test case for id_scheda_verifica

        API Rest per la validazione di una Scheda dati. ASINCRONO - ASIMMETRICO  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
