# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnacFormS4Type(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cig': 'str',
        'partecipante': 'PartecipanteType',
        'motivo_variazione': 'MotiviVariazioneAnagraficaEnum'
    }

    attribute_map = {
        'cig': 'cig',
        'partecipante': 'partecipante',
        'motivo_variazione': 'motivoVariazione'
    }

    def __init__(self, cig=None, partecipante=None, motivo_variazione=None):  # noqa: E501
        """AnacFormS4Type - a model defined in Swagger"""  # noqa: E501
        self._cig = None
        self._partecipante = None
        self._motivo_variazione = None
        self.discriminator = None
        self.cig = cig
        if partecipante is not None:
            self.partecipante = partecipante
        if motivo_variazione is not None:
            self.motivo_variazione = motivo_variazione

    @property
    def cig(self):
        """Gets the cig of this AnacFormS4Type.  # noqa: E501

        codice identificativo lotto  # noqa: E501

        :return: The cig of this AnacFormS4Type.  # noqa: E501
        :rtype: str
        """
        return self._cig

    @cig.setter
    def cig(self, cig):
        """Sets the cig of this AnacFormS4Type.

        codice identificativo lotto  # noqa: E501

        :param cig: The cig of this AnacFormS4Type.  # noqa: E501
        :type: str
        """
        if cig is None:
            raise ValueError("Invalid value for `cig`, must not be `None`")  # noqa: E501

        self._cig = cig

    @property
    def partecipante(self):
        """Gets the partecipante of this AnacFormS4Type.  # noqa: E501


        :return: The partecipante of this AnacFormS4Type.  # noqa: E501
        :rtype: PartecipanteType
        """
        return self._partecipante

    @partecipante.setter
    def partecipante(self, partecipante):
        """Sets the partecipante of this AnacFormS4Type.


        :param partecipante: The partecipante of this AnacFormS4Type.  # noqa: E501
        :type: PartecipanteType
        """

        self._partecipante = partecipante

    @property
    def motivo_variazione(self):
        """Gets the motivo_variazione of this AnacFormS4Type.  # noqa: E501


        :return: The motivo_variazione of this AnacFormS4Type.  # noqa: E501
        :rtype: MotiviVariazioneAnagraficaEnum
        """
        return self._motivo_variazione

    @motivo_variazione.setter
    def motivo_variazione(self, motivo_variazione):
        """Sets the motivo_variazione of this AnacFormS4Type.


        :param motivo_variazione: The motivo_variazione of this AnacFormS4Type.  # noqa: E501
        :type: MotiviVariazioneAnagraficaEnum
        """

        self._motivo_variazione = motivo_variazione

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnacFormS4Type, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnacFormS4Type):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
