# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AppaltoA36Type(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'codice_appalto': 'str',
        'relazione_unica_sulle_procedure': 'bool'
    }

    attribute_map = {
        'codice_appalto': 'codiceAppalto',
        'relazione_unica_sulle_procedure': 'relazioneUnicaSulleProcedure'
    }

    def __init__(self, codice_appalto=None, relazione_unica_sulle_procedure=None):  # noqa: E501
        """AppaltoA36Type - a model defined in Swagger"""  # noqa: E501
        self._codice_appalto = None
        self._relazione_unica_sulle_procedure = None
        self.discriminator = None
        self.codice_appalto = codice_appalto
        self.relazione_unica_sulle_procedure = relazione_unica_sulle_procedure

    @property
    def codice_appalto(self):
        """Gets the codice_appalto of this AppaltoA36Type.  # noqa: E501

        Identificativo univoco dell'appalto definito dalla Stazione Appaltante  # noqa: E501

        :return: The codice_appalto of this AppaltoA36Type.  # noqa: E501
        :rtype: str
        """
        return self._codice_appalto

    @codice_appalto.setter
    def codice_appalto(self, codice_appalto):
        """Sets the codice_appalto of this AppaltoA36Type.

        Identificativo univoco dell'appalto definito dalla Stazione Appaltante  # noqa: E501

        :param codice_appalto: The codice_appalto of this AppaltoA36Type.  # noqa: E501
        :type: str
        """
        if codice_appalto is None:
            raise ValueError("Invalid value for `codice_appalto`, must not be `None`")  # noqa: E501

        self._codice_appalto = codice_appalto

    @property
    def relazione_unica_sulle_procedure(self):
        """Gets the relazione_unica_sulle_procedure of this AppaltoA36Type.  # noqa: E501

        Il sottoscritto dichiara che questa SA ha redatto la Relazione Unica sulle Procedure  # noqa: E501

        :return: The relazione_unica_sulle_procedure of this AppaltoA36Type.  # noqa: E501
        :rtype: bool
        """
        return self._relazione_unica_sulle_procedure

    @relazione_unica_sulle_procedure.setter
    def relazione_unica_sulle_procedure(self, relazione_unica_sulle_procedure):
        """Sets the relazione_unica_sulle_procedure of this AppaltoA36Type.

        Il sottoscritto dichiara che questa SA ha redatto la Relazione Unica sulle Procedure  # noqa: E501

        :param relazione_unica_sulle_procedure: The relazione_unica_sulle_procedure of this AppaltoA36Type.  # noqa: E501
        :type: bool
        """
        if relazione_unica_sulle_procedure is None:
            raise ValueError("Invalid value for `relazione_unica_sulle_procedure`, must not be `None`")  # noqa: E501

        self._relazione_unica_sulle_procedure = relazione_unica_sulle_procedure

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppaltoA36Type, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppaltoA36Type):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
