# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AppaltoA32Type(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'modalita_riaggiudicazione_affidamento': 'ModalitaRiaggiudicazioneAffidamentoEnum',
        'dati_base_subappalti': 'AllOfAppaltoA32TypeDatiBaseSubappalti'
    }

    attribute_map = {
        'modalita_riaggiudicazione_affidamento': 'modalitaRiaggiudicazioneAffidamento',
        'dati_base_subappalti': 'datiBaseSubappalti'
    }

    def __init__(self, modalita_riaggiudicazione_affidamento=None, dati_base_subappalti=None):  # noqa: E501
        """AppaltoA32Type - a model defined in Swagger"""  # noqa: E501
        self._modalita_riaggiudicazione_affidamento = None
        self._dati_base_subappalti = None
        self.discriminator = None
        if modalita_riaggiudicazione_affidamento is not None:
            self.modalita_riaggiudicazione_affidamento = modalita_riaggiudicazione_affidamento
        if dati_base_subappalti is not None:
            self.dati_base_subappalti = dati_base_subappalti

    @property
    def modalita_riaggiudicazione_affidamento(self):
        """Gets the modalita_riaggiudicazione_affidamento of this AppaltoA32Type.  # noqa: E501


        :return: The modalita_riaggiudicazione_affidamento of this AppaltoA32Type.  # noqa: E501
        :rtype: ModalitaRiaggiudicazioneAffidamentoEnum
        """
        return self._modalita_riaggiudicazione_affidamento

    @modalita_riaggiudicazione_affidamento.setter
    def modalita_riaggiudicazione_affidamento(self, modalita_riaggiudicazione_affidamento):
        """Sets the modalita_riaggiudicazione_affidamento of this AppaltoA32Type.


        :param modalita_riaggiudicazione_affidamento: The modalita_riaggiudicazione_affidamento of this AppaltoA32Type.  # noqa: E501
        :type: ModalitaRiaggiudicazioneAffidamentoEnum
        """

        self._modalita_riaggiudicazione_affidamento = modalita_riaggiudicazione_affidamento

    @property
    def dati_base_subappalti(self):
        """Gets the dati_base_subappalti of this AppaltoA32Type.  # noqa: E501


        :return: The dati_base_subappalti of this AppaltoA32Type.  # noqa: E501
        :rtype: AllOfAppaltoA32TypeDatiBaseSubappalti
        """
        return self._dati_base_subappalti

    @dati_base_subappalti.setter
    def dati_base_subappalti(self, dati_base_subappalti):
        """Sets the dati_base_subappalti of this AppaltoA32Type.


        :param dati_base_subappalti: The dati_base_subappalti of this AppaltoA32Type.  # noqa: E501
        :type: AllOfAppaltoA32TypeDatiBaseSubappalti
        """

        self._dati_base_subappalti = dati_base_subappalti

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppaltoA32Type, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppaltoA32Type):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
