# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BaseResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instance': 'str',
        'status': 'int',
        'title': 'str',
        'detail': 'str',
        'type': 'str'
    }

    attribute_map = {
        'instance': 'instance',
        'status': 'status',
        'title': 'title',
        'detail': 'detail',
        'type': 'type'
    }

    def __init__(self, instance=None, status=None, title=None, detail=None, type='about:blank'):  # noqa: E501
        """BaseResponse - a model defined in Swagger"""  # noqa: E501
        self._instance = None
        self._status = None
        self._title = None
        self._detail = None
        self._type = None
        self.discriminator = None
        if instance is not None:
            self.instance = instance
        if status is not None:
            self.status = status
        if title is not None:
            self.title = title
        if detail is not None:
            self.detail = detail
        if type is not None:
            self.type = type

    @property
    def instance(self):
        """Gets the instance of this BaseResponse.  # noqa: E501

        An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.   # noqa: E501

        :return: The instance of this BaseResponse.  # noqa: E501
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this BaseResponse.

        An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.   # noqa: E501

        :param instance: The instance of this BaseResponse.  # noqa: E501
        :type: str
        """

        self._instance = instance

    @property
    def status(self):
        """Gets the status of this BaseResponse.  # noqa: E501

        The HTTP status code generated by the origin server for this occurrence of the problem.   # noqa: E501

        :return: The status of this BaseResponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this BaseResponse.

        The HTTP status code generated by the origin server for this occurrence of the problem.   # noqa: E501

        :param status: The status of this BaseResponse.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def title(self):
        """Gets the title of this BaseResponse.  # noqa: E501

        A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized);   # noqa: E501

        :return: The title of this BaseResponse.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BaseResponse.

        A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized);   # noqa: E501

        :param title: The title of this BaseResponse.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def detail(self):
        """Gets the detail of this BaseResponse.  # noqa: E501

        A human readable explanation specific to this occurrence of the problem.   # noqa: E501

        :return: The detail of this BaseResponse.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this BaseResponse.

        A human readable explanation specific to this occurrence of the problem.   # noqa: E501

        :param detail: The detail of this BaseResponse.  # noqa: E501
        :type: str
        """

        self._detail = detail

    @property
    def type(self):
        """Gets the type of this BaseResponse.  # noqa: E501

        An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).   # noqa: E501

        :return: The type of this BaseResponse.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BaseResponse.

        An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).   # noqa: E501

        :param type: The type of this BaseResponse.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BaseResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BaseResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
