# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatiPersonaGiuridicaType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'codice_fiscale': 'str',
        'denominazione': 'str',
        'ruolo_oe': 'RuoloOEEnum',
        'tipo_oe': 'TipoOEEnum',
        'id_gruppo': 'float'
    }

    attribute_map = {
        'codice_fiscale': 'codiceFiscale',
        'denominazione': 'denominazione',
        'ruolo_oe': 'ruoloOE',
        'tipo_oe': 'tipoOE',
        'id_gruppo': 'idGruppo'
    }

    def __init__(self, codice_fiscale=None, denominazione=None, ruolo_oe=None, tipo_oe=None, id_gruppo=None):  # noqa: E501
        """DatiPersonaGiuridicaType - a model defined in Swagger"""  # noqa: E501
        self._codice_fiscale = None
        self._denominazione = None
        self._ruolo_oe = None
        self._tipo_oe = None
        self._id_gruppo = None
        self.discriminator = None
        if codice_fiscale is not None:
            self.codice_fiscale = codice_fiscale
        if denominazione is not None:
            self.denominazione = denominazione
        if ruolo_oe is not None:
            self.ruolo_oe = ruolo_oe
        if tipo_oe is not None:
            self.tipo_oe = tipo_oe
        if id_gruppo is not None:
            self.id_gruppo = id_gruppo

    @property
    def codice_fiscale(self):
        """Gets the codice_fiscale of this DatiPersonaGiuridicaType.  # noqa: E501

        Codice fiscale  # noqa: E501

        :return: The codice_fiscale of this DatiPersonaGiuridicaType.  # noqa: E501
        :rtype: str
        """
        return self._codice_fiscale

    @codice_fiscale.setter
    def codice_fiscale(self, codice_fiscale):
        """Sets the codice_fiscale of this DatiPersonaGiuridicaType.

        Codice fiscale  # noqa: E501

        :param codice_fiscale: The codice_fiscale of this DatiPersonaGiuridicaType.  # noqa: E501
        :type: str
        """

        self._codice_fiscale = codice_fiscale

    @property
    def denominazione(self):
        """Gets the denominazione of this DatiPersonaGiuridicaType.  # noqa: E501

        Denominazione  # noqa: E501

        :return: The denominazione of this DatiPersonaGiuridicaType.  # noqa: E501
        :rtype: str
        """
        return self._denominazione

    @denominazione.setter
    def denominazione(self, denominazione):
        """Sets the denominazione of this DatiPersonaGiuridicaType.

        Denominazione  # noqa: E501

        :param denominazione: The denominazione of this DatiPersonaGiuridicaType.  # noqa: E501
        :type: str
        """

        self._denominazione = denominazione

    @property
    def ruolo_oe(self):
        """Gets the ruolo_oe of this DatiPersonaGiuridicaType.  # noqa: E501


        :return: The ruolo_oe of this DatiPersonaGiuridicaType.  # noqa: E501
        :rtype: RuoloOEEnum
        """
        return self._ruolo_oe

    @ruolo_oe.setter
    def ruolo_oe(self, ruolo_oe):
        """Sets the ruolo_oe of this DatiPersonaGiuridicaType.


        :param ruolo_oe: The ruolo_oe of this DatiPersonaGiuridicaType.  # noqa: E501
        :type: RuoloOEEnum
        """

        self._ruolo_oe = ruolo_oe

    @property
    def tipo_oe(self):
        """Gets the tipo_oe of this DatiPersonaGiuridicaType.  # noqa: E501


        :return: The tipo_oe of this DatiPersonaGiuridicaType.  # noqa: E501
        :rtype: TipoOEEnum
        """
        return self._tipo_oe

    @tipo_oe.setter
    def tipo_oe(self, tipo_oe):
        """Sets the tipo_oe of this DatiPersonaGiuridicaType.


        :param tipo_oe: The tipo_oe of this DatiPersonaGiuridicaType.  # noqa: E501
        :type: TipoOEEnum
        """

        self._tipo_oe = tipo_oe

    @property
    def id_gruppo(self):
        """Gets the id_gruppo of this DatiPersonaGiuridicaType.  # noqa: E501

        id gruppo  # noqa: E501

        :return: The id_gruppo of this DatiPersonaGiuridicaType.  # noqa: E501
        :rtype: float
        """
        return self._id_gruppo

    @id_gruppo.setter
    def id_gruppo(self, id_gruppo):
        """Sets the id_gruppo of this DatiPersonaGiuridicaType.

        id gruppo  # noqa: E501

        :param id_gruppo: The id_gruppo of this DatiPersonaGiuridicaType.  # noqa: E501
        :type: float
        """

        self._id_gruppo = id_gruppo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatiPersonaGiuridicaType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatiPersonaGiuridicaType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
