# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatiBaseDurataType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_inizio': 'datetime',
        'durata': 'float',
        'data_fine': 'datetime',
        'altra_durata': 'AltraDurataEnum'
    }

    attribute_map = {
        'data_inizio': 'dataInizio',
        'durata': 'durata',
        'data_fine': 'dataFine',
        'altra_durata': 'altraDurata'
    }

    def __init__(self, data_inizio=None, durata=None, data_fine=None, altra_durata=None):  # noqa: E501
        """DatiBaseDurataType - a model defined in Swagger"""  # noqa: E501
        self._data_inizio = None
        self._durata = None
        self._data_fine = None
        self._altra_durata = None
        self.discriminator = None
        if data_inizio is not None:
            self.data_inizio = data_inizio
        if durata is not None:
            self.durata = durata
        if data_fine is not None:
            self.data_fine = data_fine
        if altra_durata is not None:
            self.altra_durata = altra_durata

    @property
    def data_inizio(self):
        """Gets the data_inizio of this DatiBaseDurataType.  # noqa: E501

        La data (stimata) alla quale ha inizio l'appalto, l'accordo quadro, il sistema dinamico di acquisizione o il sistema di qualificazione. - corrisponde al campo bt-536 - Duration Start Date del TED  # noqa: E501

        :return: The data_inizio of this DatiBaseDurataType.  # noqa: E501
        :rtype: datetime
        """
        return self._data_inizio

    @data_inizio.setter
    def data_inizio(self, data_inizio):
        """Sets the data_inizio of this DatiBaseDurataType.

        La data (stimata) alla quale ha inizio l'appalto, l'accordo quadro, il sistema dinamico di acquisizione o il sistema di qualificazione. - corrisponde al campo bt-536 - Duration Start Date del TED  # noqa: E501

        :param data_inizio: The data_inizio of this DatiBaseDurataType.  # noqa: E501
        :type: datetime
        """

        self._data_inizio = data_inizio

    @property
    def durata(self):
        """Gets the durata of this DatiBaseDurataType.  # noqa: E501

        Il periodo (stimato) che intercorre tra l'inizio e la fine dell'appalto, dell'accordo quadro, del sistema dinamico di acquisizione o del sistema di qualificazione. Sono compresi tutte le opzioni e tutti i rinnovi. - corrisponde al campo bt-36 - Duration Period del TED  # noqa: E501

        :return: The durata of this DatiBaseDurataType.  # noqa: E501
        :rtype: float
        """
        return self._durata

    @durata.setter
    def durata(self, durata):
        """Sets the durata of this DatiBaseDurataType.

        Il periodo (stimato) che intercorre tra l'inizio e la fine dell'appalto, dell'accordo quadro, del sistema dinamico di acquisizione o del sistema di qualificazione. Sono compresi tutte le opzioni e tutti i rinnovi. - corrisponde al campo bt-36 - Duration Period del TED  # noqa: E501

        :param durata: The durata of this DatiBaseDurataType.  # noqa: E501
        :type: float
        """

        self._durata = durata

    @property
    def data_fine(self):
        """Gets the data_fine of this DatiBaseDurataType.  # noqa: E501

        La data (stimata) alla quale ha fine l'appalto, l'accordo quadro, il sistema dinamico di acquisizione o il sistema di qualificazione. - corrisponde al campo bt-537 - Duration End Date del TED  # noqa: E501

        :return: The data_fine of this DatiBaseDurataType.  # noqa: E501
        :rtype: datetime
        """
        return self._data_fine

    @data_fine.setter
    def data_fine(self, data_fine):
        """Sets the data_fine of this DatiBaseDurataType.

        La data (stimata) alla quale ha fine l'appalto, l'accordo quadro, il sistema dinamico di acquisizione o il sistema di qualificazione. - corrisponde al campo bt-537 - Duration End Date del TED  # noqa: E501

        :param data_fine: The data_fine of this DatiBaseDurataType.  # noqa: E501
        :type: datetime
        """

        self._data_fine = data_fine

    @property
    def altra_durata(self):
        """Gets the altra_durata of this DatiBaseDurataType.  # noqa: E501


        :return: The altra_durata of this DatiBaseDurataType.  # noqa: E501
        :rtype: AltraDurataEnum
        """
        return self._altra_durata

    @altra_durata.setter
    def altra_durata(self, altra_durata):
        """Sets the altra_durata of this DatiBaseDurataType.


        :param altra_durata: The altra_durata of this DatiBaseDurataType.  # noqa: E501
        :type: AltraDurataEnum
        """

        self._altra_durata = altra_durata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatiBaseDurataType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatiBaseDurataType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
