# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatiBaseCPVPLBaseType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tipo_classificazione': 'TipoClassificazioneEnum',
        'cpv_prevalente': 'CPVEnum'
    }

    attribute_map = {
        'tipo_classificazione': 'tipoClassificazione',
        'cpv_prevalente': 'cpvPrevalente'
    }

    def __init__(self, tipo_classificazione=None, cpv_prevalente=None):  # noqa: E501
        """DatiBaseCPVPLBaseType - a model defined in Swagger"""  # noqa: E501
        self._tipo_classificazione = None
        self._cpv_prevalente = None
        self.discriminator = None
        if tipo_classificazione is not None:
            self.tipo_classificazione = tipo_classificazione
        self.cpv_prevalente = cpv_prevalente

    @property
    def tipo_classificazione(self):
        """Gets the tipo_classificazione of this DatiBaseCPVPLBaseType.  # noqa: E501


        :return: The tipo_classificazione of this DatiBaseCPVPLBaseType.  # noqa: E501
        :rtype: TipoClassificazioneEnum
        """
        return self._tipo_classificazione

    @tipo_classificazione.setter
    def tipo_classificazione(self, tipo_classificazione):
        """Sets the tipo_classificazione of this DatiBaseCPVPLBaseType.


        :param tipo_classificazione: The tipo_classificazione of this DatiBaseCPVPLBaseType.  # noqa: E501
        :type: TipoClassificazioneEnum
        """

        self._tipo_classificazione = tipo_classificazione

    @property
    def cpv_prevalente(self):
        """Gets the cpv_prevalente of this DatiBaseCPVPLBaseType.  # noqa: E501


        :return: The cpv_prevalente of this DatiBaseCPVPLBaseType.  # noqa: E501
        :rtype: CPVEnum
        """
        return self._cpv_prevalente

    @cpv_prevalente.setter
    def cpv_prevalente(self, cpv_prevalente):
        """Sets the cpv_prevalente of this DatiBaseCPVPLBaseType.


        :param cpv_prevalente: The cpv_prevalente of this DatiBaseCPVPLBaseType.  # noqa: E501
        :type: CPVEnum
        """
        if cpv_prevalente is None:
            raise ValueError("Invalid value for `cpv_prevalente`, must not be `None`")  # noqa: E501

        self._cpv_prevalente = cpv_prevalente

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatiBaseCPVPLBaseType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatiBaseCPVPLBaseType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
