# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DatiPubblicazioneITType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data_controllo': 'datetime',
        'data_inoltro_pubblicazione': 'datetime',
        'data_pubblicazione': 'datetime',
        'stato': 'StatoAvvisoEnum',
        'tipo': 'TipoAvvisoEnum'
    }

    attribute_map = {
        'data_controllo': 'dataControllo',
        'data_inoltro_pubblicazione': 'dataInoltroPubblicazione',
        'data_pubblicazione': 'dataPubblicazione',
        'stato': 'stato',
        'tipo': 'tipo'
    }

    def __init__(self, data_controllo=None, data_inoltro_pubblicazione=None, data_pubblicazione=None, stato=None, tipo=None):  # noqa: E501
        """DatiPubblicazioneITType - a model defined in Swagger"""  # noqa: E501
        self._data_controllo = None
        self._data_inoltro_pubblicazione = None
        self._data_pubblicazione = None
        self._stato = None
        self._tipo = None
        self.discriminator = None
        if data_controllo is not None:
            self.data_controllo = data_controllo
        if data_inoltro_pubblicazione is not None:
            self.data_inoltro_pubblicazione = data_inoltro_pubblicazione
        if data_pubblicazione is not None:
            self.data_pubblicazione = data_pubblicazione
        if stato is not None:
            self.stato = stato
        if tipo is not None:
            self.tipo = tipo

    @property
    def data_controllo(self):
        """Gets the data_controllo of this DatiPubblicazioneITType.  # noqa: E501

        data in cui è stato effettuato il controllo dello stato avviso sulla PPL nazionale (A date-time specified by ISO 8601 as profiled by RFC 3339)  # noqa: E501

        :return: The data_controllo of this DatiPubblicazioneITType.  # noqa: E501
        :rtype: datetime
        """
        return self._data_controllo

    @data_controllo.setter
    def data_controllo(self, data_controllo):
        """Sets the data_controllo of this DatiPubblicazioneITType.

        data in cui è stato effettuato il controllo dello stato avviso sulla PPL nazionale (A date-time specified by ISO 8601 as profiled by RFC 3339)  # noqa: E501

        :param data_controllo: The data_controllo of this DatiPubblicazioneITType.  # noqa: E501
        :type: datetime
        """

        self._data_controllo = data_controllo

    @property
    def data_inoltro_pubblicazione(self):
        """Gets the data_inoltro_pubblicazione of this DatiPubblicazioneITType.  # noqa: E501

        data in cui è stato effettuato l'invio dell'avviso alla PPL nazionale (A date-time specified by ISO 8601 as profiled by RFC 3339)  # noqa: E501

        :return: The data_inoltro_pubblicazione of this DatiPubblicazioneITType.  # noqa: E501
        :rtype: datetime
        """
        return self._data_inoltro_pubblicazione

    @data_inoltro_pubblicazione.setter
    def data_inoltro_pubblicazione(self, data_inoltro_pubblicazione):
        """Sets the data_inoltro_pubblicazione of this DatiPubblicazioneITType.

        data in cui è stato effettuato l'invio dell'avviso alla PPL nazionale (A date-time specified by ISO 8601 as profiled by RFC 3339)  # noqa: E501

        :param data_inoltro_pubblicazione: The data_inoltro_pubblicazione of this DatiPubblicazioneITType.  # noqa: E501
        :type: datetime
        """

        self._data_inoltro_pubblicazione = data_inoltro_pubblicazione

    @property
    def data_pubblicazione(self):
        """Gets the data_pubblicazione of this DatiPubblicazioneITType.  # noqa: E501

        data di pubblicazione dell'Avviso comunicata dalla PPL nazionale (A date-time specified by ISO 8601 as profiled by RFC 3339)  # noqa: E501

        :return: The data_pubblicazione of this DatiPubblicazioneITType.  # noqa: E501
        :rtype: datetime
        """
        return self._data_pubblicazione

    @data_pubblicazione.setter
    def data_pubblicazione(self, data_pubblicazione):
        """Sets the data_pubblicazione of this DatiPubblicazioneITType.

        data di pubblicazione dell'Avviso comunicata dalla PPL nazionale (A date-time specified by ISO 8601 as profiled by RFC 3339)  # noqa: E501

        :param data_pubblicazione: The data_pubblicazione of this DatiPubblicazioneITType.  # noqa: E501
        :type: datetime
        """

        self._data_pubblicazione = data_pubblicazione

    @property
    def stato(self):
        """Gets the stato of this DatiPubblicazioneITType.  # noqa: E501


        :return: The stato of this DatiPubblicazioneITType.  # noqa: E501
        :rtype: StatoAvvisoEnum
        """
        return self._stato

    @stato.setter
    def stato(self, stato):
        """Sets the stato of this DatiPubblicazioneITType.


        :param stato: The stato of this DatiPubblicazioneITType.  # noqa: E501
        :type: StatoAvvisoEnum
        """

        self._stato = stato

    @property
    def tipo(self):
        """Gets the tipo of this DatiPubblicazioneITType.  # noqa: E501


        :return: The tipo of this DatiPubblicazioneITType.  # noqa: E501
        :rtype: TipoAvvisoEnum
        """
        return self._tipo

    @tipo.setter
    def tipo(self, tipo):
        """Sets the tipo of this DatiPubblicazioneITType.


        :param tipo: The tipo of this DatiPubblicazioneITType.  # noqa: E501
        :type: TipoAvvisoEnum
        """

        self._tipo = tipo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DatiPubblicazioneITType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DatiPubblicazioneITType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
