# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FinanziamentoType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tipo_finanziamento': 'TipoFinanziamentoEnum',
        'importo': 'ImportoType'
    }

    attribute_map = {
        'tipo_finanziamento': 'tipoFinanziamento',
        'importo': 'importo'
    }

    def __init__(self, tipo_finanziamento=None, importo=None):  # noqa: E501
        """FinanziamentoType - a model defined in Swagger"""  # noqa: E501
        self._tipo_finanziamento = None
        self._importo = None
        self.discriminator = None
        self.tipo_finanziamento = tipo_finanziamento
        self.importo = importo

    @property
    def tipo_finanziamento(self):
        """Gets the tipo_finanziamento of this FinanziamentoType.  # noqa: E501


        :return: The tipo_finanziamento of this FinanziamentoType.  # noqa: E501
        :rtype: TipoFinanziamentoEnum
        """
        return self._tipo_finanziamento

    @tipo_finanziamento.setter
    def tipo_finanziamento(self, tipo_finanziamento):
        """Sets the tipo_finanziamento of this FinanziamentoType.


        :param tipo_finanziamento: The tipo_finanziamento of this FinanziamentoType.  # noqa: E501
        :type: TipoFinanziamentoEnum
        """
        if tipo_finanziamento is None:
            raise ValueError("Invalid value for `tipo_finanziamento`, must not be `None`")  # noqa: E501

        self._tipo_finanziamento = tipo_finanziamento

    @property
    def importo(self):
        """Gets the importo of this FinanziamentoType.  # noqa: E501


        :return: The importo of this FinanziamentoType.  # noqa: E501
        :rtype: ImportoType
        """
        return self._importo

    @importo.setter
    def importo(self, importo):
        """Sets the importo of this FinanziamentoType.


        :param importo: The importo of this FinanziamentoType.  # noqa: E501
        :type: ImportoType
        """
        if importo is None:
            raise ValueError("Invalid value for `importo`, must not be `None`")  # noqa: E501

        self._importo = importo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FinanziamentoType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FinanziamentoType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
