# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IncaricoType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tipo_incarico': 'TipoIncaricoEnum',
        'dati_persona_fisica': 'DatiPersonaFisicaType',
        'dati_persona_giuridica': 'list[DatiPersonaGiuridicaType]'
    }

    attribute_map = {
        'tipo_incarico': 'tipoIncarico',
        'dati_persona_fisica': 'datiPersonaFisica',
        'dati_persona_giuridica': 'datiPersonaGiuridica'
    }

    def __init__(self, tipo_incarico=None, dati_persona_fisica=None, dati_persona_giuridica=None):  # noqa: E501
        """IncaricoType - a model defined in Swagger"""  # noqa: E501
        self._tipo_incarico = None
        self._dati_persona_fisica = None
        self._dati_persona_giuridica = None
        self.discriminator = None
        if tipo_incarico is not None:
            self.tipo_incarico = tipo_incarico
        if dati_persona_fisica is not None:
            self.dati_persona_fisica = dati_persona_fisica
        if dati_persona_giuridica is not None:
            self.dati_persona_giuridica = dati_persona_giuridica

    @property
    def tipo_incarico(self):
        """Gets the tipo_incarico of this IncaricoType.  # noqa: E501


        :return: The tipo_incarico of this IncaricoType.  # noqa: E501
        :rtype: TipoIncaricoEnum
        """
        return self._tipo_incarico

    @tipo_incarico.setter
    def tipo_incarico(self, tipo_incarico):
        """Sets the tipo_incarico of this IncaricoType.


        :param tipo_incarico: The tipo_incarico of this IncaricoType.  # noqa: E501
        :type: TipoIncaricoEnum
        """

        self._tipo_incarico = tipo_incarico

    @property
    def dati_persona_fisica(self):
        """Gets the dati_persona_fisica of this IncaricoType.  # noqa: E501


        :return: The dati_persona_fisica of this IncaricoType.  # noqa: E501
        :rtype: DatiPersonaFisicaType
        """
        return self._dati_persona_fisica

    @dati_persona_fisica.setter
    def dati_persona_fisica(self, dati_persona_fisica):
        """Sets the dati_persona_fisica of this IncaricoType.


        :param dati_persona_fisica: The dati_persona_fisica of this IncaricoType.  # noqa: E501
        :type: DatiPersonaFisicaType
        """

        self._dati_persona_fisica = dati_persona_fisica

    @property
    def dati_persona_giuridica(self):
        """Gets the dati_persona_giuridica of this IncaricoType.  # noqa: E501


        :return: The dati_persona_giuridica of this IncaricoType.  # noqa: E501
        :rtype: list[DatiPersonaGiuridicaType]
        """
        return self._dati_persona_giuridica

    @dati_persona_giuridica.setter
    def dati_persona_giuridica(self, dati_persona_giuridica):
        """Sets the dati_persona_giuridica of this IncaricoType.


        :param dati_persona_giuridica: The dati_persona_giuridica of this IncaricoType.  # noqa: E501
        :type: list[DatiPersonaGiuridicaType]
        """

        self._dati_persona_giuridica = dati_persona_giuridica

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IncaricoType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IncaricoType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
