# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PrestazioneType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'progettazione_interna_esterna': 'str',
        'tipo_soggetto': 'TipoSoggettoEnum',
        'dati_persona_fisica': 'DatiPersonaFisicaType',
        'dati_persona_giuridica': 'list[DatiPersonaGiuridicaType]',
        'tipo_progettazione': 'TipoProgettazioneEnum',
        'cig': 'str',
        'data_affidamento_incarico': 'datetime',
        'data_consegna': 'datetime'
    }

    attribute_map = {
        'progettazione_interna_esterna': 'progettazioneInternaEsterna',
        'tipo_soggetto': 'tipoSoggetto',
        'dati_persona_fisica': 'datiPersonaFisica',
        'dati_persona_giuridica': 'datiPersonaGiuridica',
        'tipo_progettazione': 'tipoProgettazione',
        'cig': 'cig',
        'data_affidamento_incarico': 'dataAffidamentoIncarico',
        'data_consegna': 'dataConsegna'
    }

    def __init__(self, progettazione_interna_esterna=None, tipo_soggetto=None, dati_persona_fisica=None, dati_persona_giuridica=None, tipo_progettazione=None, cig=None, data_affidamento_incarico=None, data_consegna=None):  # noqa: E501
        """PrestazioneType - a model defined in Swagger"""  # noqa: E501
        self._progettazione_interna_esterna = None
        self._tipo_soggetto = None
        self._dati_persona_fisica = None
        self._dati_persona_giuridica = None
        self._tipo_progettazione = None
        self._cig = None
        self._data_affidamento_incarico = None
        self._data_consegna = None
        self.discriminator = None
        if progettazione_interna_esterna is not None:
            self.progettazione_interna_esterna = progettazione_interna_esterna
        if tipo_soggetto is not None:
            self.tipo_soggetto = tipo_soggetto
        if dati_persona_fisica is not None:
            self.dati_persona_fisica = dati_persona_fisica
        if dati_persona_giuridica is not None:
            self.dati_persona_giuridica = dati_persona_giuridica
        if tipo_progettazione is not None:
            self.tipo_progettazione = tipo_progettazione
        if cig is not None:
            self.cig = cig
        if data_affidamento_incarico is not None:
            self.data_affidamento_incarico = data_affidamento_incarico
        if data_consegna is not None:
            self.data_consegna = data_consegna

    @property
    def progettazione_interna_esterna(self):
        """Gets the progettazione_interna_esterna of this PrestazioneType.  # noqa: E501

        La progettazione è interna o esterna?  # noqa: E501

        :return: The progettazione_interna_esterna of this PrestazioneType.  # noqa: E501
        :rtype: str
        """
        return self._progettazione_interna_esterna

    @progettazione_interna_esterna.setter
    def progettazione_interna_esterna(self, progettazione_interna_esterna):
        """Sets the progettazione_interna_esterna of this PrestazioneType.

        La progettazione è interna o esterna?  # noqa: E501

        :param progettazione_interna_esterna: The progettazione_interna_esterna of this PrestazioneType.  # noqa: E501
        :type: str
        """
        allowed_values = ["INTERNA", "ESTERNA"]  # noqa: E501
        if progettazione_interna_esterna not in allowed_values:
            raise ValueError(
                "Invalid value for `progettazione_interna_esterna` ({0}), must be one of {1}"  # noqa: E501
                .format(progettazione_interna_esterna, allowed_values)
            )

        self._progettazione_interna_esterna = progettazione_interna_esterna

    @property
    def tipo_soggetto(self):
        """Gets the tipo_soggetto of this PrestazioneType.  # noqa: E501


        :return: The tipo_soggetto of this PrestazioneType.  # noqa: E501
        :rtype: TipoSoggettoEnum
        """
        return self._tipo_soggetto

    @tipo_soggetto.setter
    def tipo_soggetto(self, tipo_soggetto):
        """Sets the tipo_soggetto of this PrestazioneType.


        :param tipo_soggetto: The tipo_soggetto of this PrestazioneType.  # noqa: E501
        :type: TipoSoggettoEnum
        """

        self._tipo_soggetto = tipo_soggetto

    @property
    def dati_persona_fisica(self):
        """Gets the dati_persona_fisica of this PrestazioneType.  # noqa: E501


        :return: The dati_persona_fisica of this PrestazioneType.  # noqa: E501
        :rtype: DatiPersonaFisicaType
        """
        return self._dati_persona_fisica

    @dati_persona_fisica.setter
    def dati_persona_fisica(self, dati_persona_fisica):
        """Sets the dati_persona_fisica of this PrestazioneType.


        :param dati_persona_fisica: The dati_persona_fisica of this PrestazioneType.  # noqa: E501
        :type: DatiPersonaFisicaType
        """

        self._dati_persona_fisica = dati_persona_fisica

    @property
    def dati_persona_giuridica(self):
        """Gets the dati_persona_giuridica of this PrestazioneType.  # noqa: E501


        :return: The dati_persona_giuridica of this PrestazioneType.  # noqa: E501
        :rtype: list[DatiPersonaGiuridicaType]
        """
        return self._dati_persona_giuridica

    @dati_persona_giuridica.setter
    def dati_persona_giuridica(self, dati_persona_giuridica):
        """Sets the dati_persona_giuridica of this PrestazioneType.


        :param dati_persona_giuridica: The dati_persona_giuridica of this PrestazioneType.  # noqa: E501
        :type: list[DatiPersonaGiuridicaType]
        """

        self._dati_persona_giuridica = dati_persona_giuridica

    @property
    def tipo_progettazione(self):
        """Gets the tipo_progettazione of this PrestazioneType.  # noqa: E501


        :return: The tipo_progettazione of this PrestazioneType.  # noqa: E501
        :rtype: TipoProgettazioneEnum
        """
        return self._tipo_progettazione

    @tipo_progettazione.setter
    def tipo_progettazione(self, tipo_progettazione):
        """Sets the tipo_progettazione of this PrestazioneType.


        :param tipo_progettazione: The tipo_progettazione of this PrestazioneType.  # noqa: E501
        :type: TipoProgettazioneEnum
        """

        self._tipo_progettazione = tipo_progettazione

    @property
    def cig(self):
        """Gets the cig of this PrestazioneType.  # noqa: E501

        CIG affidamento incarico esterno di progettazione (in caso di progettista esterno)  # noqa: E501

        :return: The cig of this PrestazioneType.  # noqa: E501
        :rtype: str
        """
        return self._cig

    @cig.setter
    def cig(self, cig):
        """Sets the cig of this PrestazioneType.

        CIG affidamento incarico esterno di progettazione (in caso di progettista esterno)  # noqa: E501

        :param cig: The cig of this PrestazioneType.  # noqa: E501
        :type: str
        """

        self._cig = cig

    @property
    def data_affidamento_incarico(self):
        """Gets the data_affidamento_incarico of this PrestazioneType.  # noqa: E501

        Data di affidamento incarico (per progettazione esterna)  # noqa: E501

        :return: The data_affidamento_incarico of this PrestazioneType.  # noqa: E501
        :rtype: datetime
        """
        return self._data_affidamento_incarico

    @data_affidamento_incarico.setter
    def data_affidamento_incarico(self, data_affidamento_incarico):
        """Sets the data_affidamento_incarico of this PrestazioneType.

        Data di affidamento incarico (per progettazione esterna)  # noqa: E501

        :param data_affidamento_incarico: The data_affidamento_incarico of this PrestazioneType.  # noqa: E501
        :type: datetime
        """

        self._data_affidamento_incarico = data_affidamento_incarico

    @property
    def data_consegna(self):
        """Gets the data_consegna of this PrestazioneType.  # noqa: E501

        Data di consegna progetto (per progettazione esterna)  # noqa: E501

        :return: The data_consegna of this PrestazioneType.  # noqa: E501
        :rtype: datetime
        """
        return self._data_consegna

    @data_consegna.setter
    def data_consegna(self, data_consegna):
        """Sets the data_consegna of this PrestazioneType.

        Data di consegna progetto (per progettazione esterna)  # noqa: E501

        :param data_consegna: The data_consegna of this PrestazioneType.  # noqa: E501
        :type: datetime
        """

        self._data_consegna = data_consegna

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrestazioneType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrestazioneType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
