# coding: utf-8

"""
    Specifiche Servizi Appalto - OpenAPI 3.0

    Sono descritte le specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ufficio.uscp@anticorruzione.it
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StatoAvvisoType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id_avviso': 'str',
        'id_appalto': 'str',
        'id_pianificazione': 'str',
        'data_controllo': 'datetime',
        'stato': 'StatoAvvisoEnum'
    }

    attribute_map = {
        'id_avviso': 'idAvviso',
        'id_appalto': 'idAppalto',
        'id_pianificazione': 'idPianificazione',
        'data_controllo': 'dataControllo',
        'stato': 'stato'
    }

    def __init__(self, id_avviso=None, id_appalto=None, id_pianificazione=None, data_controllo=None, stato=None):  # noqa: E501
        """StatoAvvisoType - a model defined in Swagger"""  # noqa: E501
        self._id_avviso = None
        self._id_appalto = None
        self._id_pianificazione = None
        self._data_controllo = None
        self._stato = None
        self.discriminator = None
        if id_avviso is not None:
            self.id_avviso = id_avviso
        if id_appalto is not None:
            self.id_appalto = id_appalto
        if id_pianificazione is not None:
            self.id_pianificazione = id_pianificazione
        if data_controllo is not None:
            self.data_controllo = data_controllo
        if stato is not None:
            self.stato = stato

    @property
    def id_avviso(self):
        """Gets the id_avviso of this StatoAvvisoType.  # noqa: E501

        identificativo univoco dell'Avviso generato da ANAC.  # noqa: E501

        :return: The id_avviso of this StatoAvvisoType.  # noqa: E501
        :rtype: str
        """
        return self._id_avviso

    @id_avviso.setter
    def id_avviso(self, id_avviso):
        """Sets the id_avviso of this StatoAvvisoType.

        identificativo univoco dell'Avviso generato da ANAC.  # noqa: E501

        :param id_avviso: The id_avviso of this StatoAvvisoType.  # noqa: E501
        :type: str
        """

        self._id_avviso = id_avviso

    @property
    def id_appalto(self):
        """Gets the id_appalto of this StatoAvvisoType.  # noqa: E501

        identificativo univoco dell'Appalto definito da ANAC. Valorizzato se l'avviso è relativo ad un Appalto. (A UUID specified by RFC4122)  # noqa: E501

        :return: The id_appalto of this StatoAvvisoType.  # noqa: E501
        :rtype: str
        """
        return self._id_appalto

    @id_appalto.setter
    def id_appalto(self, id_appalto):
        """Sets the id_appalto of this StatoAvvisoType.

        identificativo univoco dell'Appalto definito da ANAC. Valorizzato se l'avviso è relativo ad un Appalto. (A UUID specified by RFC4122)  # noqa: E501

        :param id_appalto: The id_appalto of this StatoAvvisoType.  # noqa: E501
        :type: str
        """

        self._id_appalto = id_appalto

    @property
    def id_pianificazione(self):
        """Gets the id_pianificazione of this StatoAvvisoType.  # noqa: E501

        identificativo univoco della Pianificazione definito da ANAC. Valorizzato se l'avviso è relativo ad un Piano. (A UUID specified by RFC4122)  # noqa: E501

        :return: The id_pianificazione of this StatoAvvisoType.  # noqa: E501
        :rtype: str
        """
        return self._id_pianificazione

    @id_pianificazione.setter
    def id_pianificazione(self, id_pianificazione):
        """Sets the id_pianificazione of this StatoAvvisoType.

        identificativo univoco della Pianificazione definito da ANAC. Valorizzato se l'avviso è relativo ad un Piano. (A UUID specified by RFC4122)  # noqa: E501

        :param id_pianificazione: The id_pianificazione of this StatoAvvisoType.  # noqa: E501
        :type: str
        """

        self._id_pianificazione = id_pianificazione

    @property
    def data_controllo(self):
        """Gets the data_controllo of this StatoAvvisoType.  # noqa: E501

        data in cui è stato effettuato il controllo sullo stato dell'avviso (A date-time specified by ISO 8601 as profiled by RFC 3339)  # noqa: E501

        :return: The data_controllo of this StatoAvvisoType.  # noqa: E501
        :rtype: datetime
        """
        return self._data_controllo

    @data_controllo.setter
    def data_controllo(self, data_controllo):
        """Sets the data_controllo of this StatoAvvisoType.

        data in cui è stato effettuato il controllo sullo stato dell'avviso (A date-time specified by ISO 8601 as profiled by RFC 3339)  # noqa: E501

        :param data_controllo: The data_controllo of this StatoAvvisoType.  # noqa: E501
        :type: datetime
        """

        self._data_controllo = data_controllo

    @property
    def stato(self):
        """Gets the stato of this StatoAvvisoType.  # noqa: E501


        :return: The stato of this StatoAvvisoType.  # noqa: E501
        :rtype: StatoAvvisoEnum
        """
        return self._stato

    @stato.setter
    def stato(self, stato):
        """Sets the stato of this StatoAvvisoType.


        :param stato: The stato of this StatoAvvisoType.  # noqa: E501
        :type: StatoAvvisoEnum
        """

        self._stato = stato

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatoAvvisoType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatoAvvisoType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
