openapi: 3.0.0
info:
  title: Modello Dati - Scheda RSU1 - Scheda di richiesta di subappalto.
  version: 1.0.0
components:
  schemas:
    SubappaltoType:
      description: Dati relativi ai subappalti
      type: object
      required: [codiciFiscaliOE,impresaEstera,importoPresunto,categoria,cpv]
      additionalProperties: false
      properties:    
        codiciFiscaliOE:
          description: Codici fiscali operatori economici
          type: array
          items:
            type: string
        impresaEstera:
          description: Impresa estera?
          type: boolean
        codiceFiscaleAggiudicatario:
          description: Codice fiscale ditta aggiudicatrice nel caso di aggiudicatari multipli
          type: string 
        codiceFiscaleDittaACascata:
          description: Codice fiscale ditta subappaltatrice
          type: string          
        oggetto:
          description: Lavoro/Servizio/Fornitura subappalto
          type: string
        oggettoMl:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MultilinguaType'         
        importoPresunto:
          description: Importo presunto Lavoro/ Servizio/Fornitura, subappalto
          type: number
          format: double
        categoria:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum' 
        categoriaScorporabile:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CategoriaEnum'          
        cpv:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/CPVEnum'   
    AnacFormRSU1Type:
      description: Contiene tutti i dati relativi alla scheda di Richiesta di Subappalto
      type: object
      required: [subappalto,idContratto]
      additionalProperties: false
      properties: 
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
        subappalto:
          $ref: '#/components/schemas/SubappaltoType'
    SchedaRSU1Type:
      description: Comunicazione richiesta di subappalto per qualunque procedura.
      type: object
      required: [anacForm,espd]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormRSU1Type'
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'            