openapi: 3.0.0
info:
  title: Modello Dati - Scheda ES1 - Scheda di esito subappalto.
  version: 1.0.0
components:
  schemas:
    SubappaltoType:
      description: Dati relativi ai subappalti
      type: object
      additionalProperties: false
      properties:    
        dataAutorizzazione: 
          description: Data di autorizzazione del subappalto
          type: string
          format: date-time
        motivoMancatoSubappalto: 
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/MotivoMancatoSubappaltoEnum'
    AnacFormES1Type:
      description: Contiene tutti i dati relativi alla scheda di Richiesta di Subappalto
      type: object
      required: [subappalto, idScheda]
      additionalProperties: false
      properties: 
        idScheda:
          description: identificativo restituito dal servizio all’invio della scheda di richiesta di subappalto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
        subappalto:
          $ref: '#/components/schemas/SubappaltoType'
    SchedaES1Type:
      description: Scheda di esito subappalto
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormES1Type'