openapi: 3.0.0
info:
  title: Modello Dati - Scheda A7_1_1 - Scheda di aggiudicazione procedura negoziata senza bando pari o sopra soglia, con invio al TED di uno tra eform25, eform26,eform27,eform28.
  version: 1.0.0
components:
  schemas:
    AnacFormA7_1_1Type:
      description: Contiene tutti i dati necessari per procedura negoziata senza bando pari o sopra soglia con invio al TED
      type: object
      required: [appalto,aggiudicazioni]
      additionalProperties: false
      properties:  
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoA7Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneA7Type'
    SchedaA7_1_1Type:
      description: aggiudicazione procedura negoziata senza bando pari o sopra soglia. Articolo  76 decreto legislativo 36/2023. Articolo  158 decreto legislativo 36/2023. Articolo 18 decreto legislativo 208/2011. Articolo 127 decreto legislativo 36/2023. Articolo 128 decreto legislativo 36/2023.
      type: object
      required: [anacForm, eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA7_1_1Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'         