openapi: 3.0.0
info:
  title: Modello Dati - Scheda P1_12 - Scheda di pubblicazione avviso per un bando di gara sopra la soglia europea e sotto soglia con invio al TED dell'eform12.
  version: 1.0.0
components:
  schemas:
    AnacFormP1_12Type:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale.
      allOf: # estende la classe AnacFormBaseType
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'  
      type: object
      additionalProperties: false
      required: [appalto,lotti]
      properties:  
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP_12Type' 
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP_12Type'    
    SchedaP1_12Type:
      description: Avviso di preinformazione utilizzato come avviso di indizione di gara — direttiva generale, regime alleggerito. Articolo 75, paragrafo 1, lettera b), della direttiva 2014/24/UE. Articolo 127 comma 1 lettera b) decreto legislativo 36/2023.
      type: object
      required: [anacForm, eform,espd]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP1_12Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'         