openapi: 3.0.0
info:
  title: Modello Dati - Scheda A2_36 - Scheda relativa all'aggiudicazione sottosoglia senza invio al TED.
  version: 1.0.0
components:
  schemas:
    AppaltoA2_36Type:
      type: object
      additionalProperties: false
      properties:  
        datiBaseProcedura:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseProceduraType'                  
    AggiudicazioneA2_36Type:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneBaseType' 
      type: object
      additionalProperties: false
      required: [numeroOfferteAmmesse]
      properties: 
        numeroOfferteAmmesse:
          description: numero di offerte ammesse
          type: number
          format: integer       
        datiBaseRisultatoProcedura:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseEsitoRisultatoProceduraType'
        datiBaseAggiudicazioneAppalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneAppaltoType'
        datiBaseAccessibilita:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAccessibilitaType'      
    AnacFormA2_36Type:
      description: Contiene tutti i dati relativi all'aggiudicazione.
      type: object
      required: [appalto,aggiudicazioni]
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoA2_36Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneA2_36Type'     
    SchedaA2_36Type:
      description: Avviso sui risultati di un concorso di progettazione, direttiva generale, progettazione. Articolo 46 decreto legislativo 36/2023.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA2_36Type'          