openapi: 3.0.0
info:
  title: Modello Dati - Scheda CO2 - Scheda di conclusione.
  version: 1.0.0
components:
  schemas:
    ConclusioneType:
      description: Oggetto che riporta i dati di conclusione.
      type: object
      additionalProperties: false
      required: [dataInizio,dataUltimazione,importo]
      properties:
        dataInizio:
          description: Data di inizio
          type: string
          format: date-time
        dataUltimazione:
          description: Data di ultimazione
          type: string
          format: date-time
        importo: 
          description: Importo delle somme liquidate
          type: number
          format: double
    AnacFormCO2Type:
      description: Contiene tutti i dati di conclusione
      type: object
      additionalProperties: false
      required: [cig, conclusione]      
      properties: 
        cig:
          description: codice identificativo lotto
          type: string      
        conclusione:
          $ref: '#/components/schemas/ConclusioneType'
    SchedaCO2Type:
      description: Scheda di conclusione
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormCO2Type'