openapi: 3.0.0
info:
  title: Modello Dati - Scheda A3_2 - Scheda di aggiudicazione relativa ai Contratti esclusi in Concessione o Contratti esclusi in Concessione con la tecnica dell'AQ
  version: 1.0.0
components:
  schemas:
    AppaltoA3_2Type:
      type: object
      additionalProperties: false
      properties:  
        modalitaRiaggiudicazioneAffidamento:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModalitaRiaggiudicazioneAffidamentoEnum'       
        datiBaseSubappalti:
          allOf: 
          - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSubappaltiType'        
    AggiudicazioneA3_2Type:
      description: Oggetto che riporta i dati inerenti la fase di aggiudicazione
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneBaseType'      
      type: object
      additionalProperties: false
      properties:        
        valoreSogliaAnomalia:
          description: Valore soglia anomalia
          type: number
          format: double
          minimum: 0
          maximum: 100         
        quadroEconomicoConcessioni:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/QuadroEconomicoConcessioniType'         
        datiBaseAggiudicazioneAppalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseAggiudicazioneAppaltoType'    
        datiBaseRisultatoProcedura:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseEsitoRisultatoProceduraType'      
        datiBaseSottomissioniRicevute:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseSottomissioniRicevuteType'          
    AnacFormA3_2Type:
      description: Contiene tutti i dati relativi all'aggiudicazione
      type: object
      required: [appalto,aggiudicazioni]
      properties:
        appalto:
          $ref: '#/components/schemas/AppaltoA3_2Type'
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: '#/components/schemas/AggiudicazioneA3_2Type'
    SchedaA3_2Type:
      description: Contratti esclusi in Concessione o Contratti esclusi in Concessione con la tecnica dell'AQ. Articolo 10 direttiva 2014/23/UE.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA3_2Type'