openapi: 3.0.0
info:
  title: Modello Dati - Scheda AC1 - Scheda di accordo bonario.
  version: 1.0.0
components:
  schemas:
    AccordoBonarioType:
      description: Oggetto che riporta tutti i dati degli accordi bonari
      type: object
      required: [dataAccordo]
      additionalProperties: false
      properties:
        dataAccordo:
          description: Data dell’accordo bonario
          type: string
          format: date-time
        oneriDerivanti:
          description: Oneri derivanti
          type: number
          format: double
        numeroRiserve:
          description: Numero di riserve transate
          type: number
          format: integer
    AnacFormAC1Type:
      description: Contiene tutti i dati relativi alla scheda di accordo bonario
      type: object
      required: [idContratto,accordoBonario]
      additionalProperties: false
      properties:
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"       
        accordoBonario:
          $ref: '#/components/schemas/AccordoBonarioType' 
    SchedaAC1Type:
      description: Accordo bonario. Articoli 210 e 211 decreto legislativo 36/2023.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormAC1Type'