openapi: 3.0.0
info:
  title: Modello Dati - Scheda A4_5 - Scheda di aggiudicazione relativa alla concessione di servizi e costruzione e gestione.
  version: 1.0.0
components:
  schemas:
    AnacFormA4_5Type:
      description: Contiene i dati per la scheda di aggiudicazione relativa alla concessione di servizi e costruzione e gestione.
      type: object
      required: [appalto,aggiudicazioni] 
      additionalProperties: false
      properties:
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoA4Type'
        aggiudicazioni:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneA4Type'    
    SchedaA4_5Type:
      description: PPP - Concessione di servizi e costruzione e gestione. Articolo 182 comma 11 secondo periodo e comma 12 decreto legislativo 36/2023.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA4_5Type'          