openapi: 3.0.0
info:
  title: Modello Dati - Scheda A1_35 - Scheda relativa all'aggiudicazione soprasoglia e sottosoglia con invio al TED dell'eform35.
  version: 1.0.0
components:
  schemas:
    AnacFormA1_35Type:
      description: Contiene tutti i dati relativi all'aggiudicazione.
      type: object
      required: [aggiudicazioni]
      additionalProperties: false
      properties:
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:        
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneA1_35Type'      
    SchedaA1_35Type:
      description: Avviso di aggiudicazione di una concessione, direttiva concessioni, regime allegerito. Articolo 32, paragrafo 2 (riferimento all’allegato. Articolo 182 comma 11 secondo periodo e comma 12 decreto legislativo 36/2023.
      type: object
      required: [anacForm, eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA1_35Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'           