openapi: 3.0.0
info:
  title: Modello Dati - Scheda P1_18 - Scheda di pubblicazione avviso per un bando di gara sopra la soglia europea e sotto soglia con invio al TED dell'eform18.
  version: 1.0.0
components:
  schemas:
    AnacFormP1_18Type:
      description: Contiene tutti i dati necessari per la pubblicazione nazionale. 
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AnacFormBaseType'      
      type: object
      additionalProperties: false
      required: [appalto, lotti]
      properties:      
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoP_18Type' 
        lotti:
          description: Dati relativi ai lotti
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/LottoP_18Type'           
    SchedaP1_18Type:
      description: Bando di gara — direttiva per il settore della difesa, regime ordinario. Articolo 30, paragrafo 2, della direttiva 2009/81/CE. Articolo 22 decreto legislativo 208/2011. Articolo 84 decreto legislativo 36/2023. Articolo 85 decreto legislativo 36/2023.
      type: object
      required: [anacForm, eform,espd]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormP1_18Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'  
        espd:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType'           
         