openapi: 3.0.0
info:
  title: Modello Dati - Scheda M1_40 - Scheda di modifica contrattuale con invio al TED dell'eform40.
  version: 1.0.0
components:
  schemas:
    AnacFormM1_40Type:
      description: Contiene tutti i dati relativi alle modifiche contrattuali
      type: object
      additionalProperties: false
      required: [idContratto, modificaContrattuale]
      properties:
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
        modificaContrattuale:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattuale_40Type' 
    SchedaM1_40Type:
      description: Modifica contrattuale, direttiva concessioni. Articolo 43, paragrafo 1, della direttiva 2014/23/UE. Articolo 189 comma 5 decreto legislativo 36/2023.
      type: object
      required: [anacForm,eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormM1_40Type'
        eform:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'           