openapi: 3.0.0
info:
  title: Modello Dati - Scheda A1_36 - Scheda relativa all'aggiudicazione soprasoglia e sottosoglia con invio al TED dell'eform36. 
  version: 1.0.0
components:
  schemas:
    AnacFormA1_36Type:
      description: Contiene tutti i dati relativi all'aggiudicazione.
      type: object
      required: [aggiudicazioni]
      additionalProperties: false
      properties:
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items: 
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneA1_36Type'
    SchedaA1_36Type:
      description: Avviso sui risultati di un concorso di progettazione, direttiva generale, progettazione. Articolo 79, paragrafo 2, della direttiva 2014/24/UE. Articolo 46 decreto legislativo 36/2023.
      type: object
      required: [anacForm, eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA1_36Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'          