openapi: 3.0.0
info:
  title: Modello Dati - Scheda M2_40 - Scheda di modifica contrattuale senza invio al TED.
  version: 1.0.0
components:
  schemas:
    ModificaContrattualeType:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattuale_40Type'
      type: object
      additionalProperties: false
      properties:    
        datiBaseModificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseModificaContrattualeType'   
    AnacFormM2_40Type:
      description: Contiene tutti i dati di modifica contrattuale
      type: object
      additionalProperties: false
      required: [idContratto,modificaContrattuale ]
      properties:  
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"        
        modificaContrattuale:
          $ref: '#/components/schemas/ModificaContrattualeType'       
    SchedaM2_40Type:
      description: Modifica contrattuale sottosoglia, concessioni. Articolo 187 comma 2 decreto legislativo 36/2023. Articolo 189 comma 5 decreto legislativo 36/2023.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormM2_40Type'