openapi: 3.0.0
info:
  title: Modello Dati - Scheda A1_33 - Scheda relativa all'aggiudicazione soprasoglia e sottosoglia con invio al TED dell'eform33.
  version: 1.0.0
components:
  schemas:
    AnacFormA1_33Type:
      description: Contiene tutti i dati relativi all'aggiudicazione.
      type: object
      required: [appalto, aggiudicazioni]
      additionalProperties: false
      properties:
        appalto:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AppaltoA1_33Type'      
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:        
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneA1_33Type'    
     
    SchedaA1_33Type:
      description: Avviso di aggiudicazione di un appalto, direttiva generale, regime allegerito. Articolo 75, paragrafo 2, della direttiva 2014/24/UE. Articolo 127 comma 3 decreto legislativo 36/2023.
      type: object
      required: [anacForm, eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA1_33Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'         