openapi: 3.0.0
info:
  title: Modello Dati - Scheda M2 - Scheda di modifica contrattuale senza invio al TED.
  version: 1.0.0
components:
  schemas:
    ModificaContrattualeType:
      allOf: 
      - $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattualeType'
      type: object
      additionalProperties: false
      properties:    
        datiBaseModificaContrattuale:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/DatiBaseModificaContrattualeType'      
    AnacFormM2Type:
      description: Contiene tutti i dati di modifica contrattuale
      type: object
      additionalProperties: false
      required: [idContratto,modificaContrattuale]
      properties:
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"       
        modificaContrattuale:
         $ref: '#/components/schemas/ModificaContrattualeType' 
          
    SchedaM2Type:
      description: Modifica contrattuale sottosoglia, generale. Articolo 72, paragrafo 1, della direttiva 2014/24/UE. Articolo 141 comma 3 lettera i) decreto o legislativo 36/2023. Articolo 120 comma 14 e comma 15 decreto legislativo 36/2023. Articolo 5 comma 11 e comma 12 Allegato II.14.
      type: object
      required: [anacForm]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormM2Type'
         