openapi: 3.0.0
info:
  title: Modello Dati - Scheda PL1_5 - Scheda di programmazione per appalti settori speciali pari /sopra soglia con invio al TED dell'eform5.
  version: 1.0.0
components:
  schemas:          
    SchedaPL1_5Type:
      description: Avviso periodico indicativo a fini unicamente informativi — direttiva settoriale. Articolo 67, paragrafo 1, della direttiva 2014/25/UE. Articolo 161 comma 1 decreto legislativo 36/2023.
      type: object
      required: [eform]
      additionalProperties: false
      properties:
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'            
         