openapi: 3.0.0
info:
  title: Modello Dati - Scheda M1 - Scheda relativa alle modifiche contrattuali con invio al TED di eform38 o eform39.
  version: 1.0.0
components:
  schemas:
    AnacFormM1Type:
      description: Contiene tutti i dati relativi alle modifiche contrattuali
      type: object
      required: [idContratto,modificaContrattuale]
      additionalProperties: false
      properties:
        idContratto:
          description: identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
          type: string   
          format: uuid
          example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"      
        modificaContrattuale:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/ModificaContrattualeType' 
    SchedaM1Type:
      description: Modifica contrattuale, direttiva generale. Articolo 72, paragrafo 1, della direttiva 2014/24/UE. Articolo 89, paragrafo 1, della direttiva 2014/25/UE. Articolo 141 comma 3 lettera i) decreto legislativo 36/2023. Articolo 120 comma 14 e comma 15 decreto legislativo 36/2023. Articolo 5 comma 11 e comma 12 Allegato II.14.
      type: object
      required: [anacForm,eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormM1Type'
        eform:
          $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'        