openapi: 3.0.0
info:
  title: Modello Dati - Scheda A1_37 - Scheda relativa all'aggiudicazione soprasoglia e sottosoglia con invio al TED dell'eform37. 
  version: 1.0.0
components:
  schemas:
    AnacFormA1_37Type:
      description: Contiene tutti i dati relativi all'aggiudicazione.
      type: object
      required: [aggiudicazioni]
      additionalProperties: false
      properties:
        aggiudicazioni:
          description: Dati relativi alle aggiudicazioni
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/AggiudicazioneA1_37Type'            
    SchedaA1_37Type:
      description: Avviso sui risultati di un concorso di progettazione, direttiva settoriale, progettazione. Articolo 96, paragrafo 1, secondo comma, della direttiva 2014/25/UE. Articolo 46 decreto legislativo 36/2023.
      type: object
      required: [anacForm, eform]
      additionalProperties: false
      properties:
        anacForm:
          $ref: '#/components/schemas/AnacFormA1_37Type'
        eform:
         $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EformType'          